// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateThumbnails(arg1:main.GenerateThumbnailsJob):Promise<number>;

export function GetSettings():Promise<main.FrontendSettings>;

export function OpenTemplate():Promise<main.FrontendTemplate>;

export function RefreshPreview():Promise<main.FrontendTemplate>;

export function SetSettings(arg1:main.FrontendSettings):Promise<void>;
