// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateThumbnails(arg1) {
  return window['go']['main']['App']['GenerateThumbnails'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenTemplate() {
  return window['go']['main']['App']['OpenTemplate']();
}

export function RefreshPreview() {
  return window['go']['main']['App']['RefreshPreview']();
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}
